// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://brcwfzwtrapbkzpolhws.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJyY3dmend0cmFwYmt6cG9saHdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NzMzNjUsImV4cCI6MjA2NjM0OTM2NX0.mn75xYoHV0YieVnACdcH7Ptt0uJ7LLq6y0wR1_sR5YM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);